docker-build:
  image: docker:latest
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
  - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
  - master
deploy:
  image:
    name: "$CI_REGISTRY_IMAGE:master"
    pull_policy: always
  stage: deploy
  script:
  - export DEBUG=false
  - export S3_UPLOAD=true
  - export S3_REGION=fr-par
  - export S3_ENDPOINT=http://s3.fr-par.scw.cloud
  - export S3_BUCKET=download.freemcserver.net
  - export S3_KEY="$S3_KEY"
  - export S3_SECRET="$S3_SECRET"
  - export S3_PULL_BASE=https://download.freemcserver.net/jar
  - export DISCORD_WEBHOOK_ENABLE=true
  - export DISCORD_WEBHOOK_URL="$DISCORD_WEBHOOK_URL"
  - cd /root/app && npm run run
  only:
  - deploy
stages:
  - build
  - deploy
  - test

