version: '3.4'
services:
  version-updater:
    image: "freemcservernet/blockupdate"
    env_file:
      - .env
    volumes:
      - ./dist:/root/app/dist/
      - ./out:/root/app/out/
      - ./tmp:/root/app/tmp/
